[app]
name = "Goer"
env = "local"
debug = true
port = 3000
timezone = "UTC"

[database]
connection = "mysql"

[database.mysql]
host = "127.0.0.1"
port = 3306
database = "goer"
username = "root"
password = ""
max_idle_connections = 10
max_open_connection = 100

[database.sqlite]
database = "database/goer.db"

[aes]
key = ""
iv = ""

[common]
uid_length = 8
default_password = ""

[jwt]
secret_key = ""
ttl = 604800

[paging]
per_page = 15

[swag]
api_doc = true
